### ISSUE TITLE
Infinite loop in Paged.js

### ISSUE THREAD

**Issue by woodbe** [Mogztter/asciidoctor-web-pdf#165]
When following the instructions to install using the command:

```
npm i -g @asciidoctor/core asciidoctor-pdf
```

I get errors about needing to copy ghostscript files from my system. I finally figured out that these weren't being compiled, but were to be copied from a specific location on my drive. I didn't have this installed by default, so it failed without me understanding why several times (I was checking for where the files were being copied to, not where they were coming from).

You should have something in the instructions that specify that ghostscript needs to be installed prior to running the npm installation command as it will fail otherwise. I was able to get to the other parts about the Windows build stuff, but there was nothing about ghostscript anywhere except in the error messages.

This may not be a problem on Linux (I haven't bothered to try there), but is definitely one on Windows.

**Comment by Mogztter** [comment]
Hello @woodbe I think it's the same error/warning as https://github.com/Mogztter/asciidoctor-pdf.js/issues/162

As far as I understand `ghostscript` is not required, it's actually an optional development dependency in [Paged.js](https://gitlab.pagedmedia.org/tools/pagedjs). We are currently discussing the best approach to fix this warning.

Can you please confirm that you can use `asciidoctor-pdf` (without installing `ghostscript`) and copy-paste the install log?

**Comment by woodbe** [comment]
I can send the install log, but at the moment it has ghostscript installed (I'm not sure where the install log is either). As for using it, no, I was not able to use it before installing ghostscript. I was getting timeout errors when the code ran which is what made me focus more on the install error messages.

**Comment by Mogztter** [comment]
> I can send the install log, but at the moment it has ghostscript installed (I'm not sure where the install log is either).

Ok. Is that possible to uninstall both ghostscript and `asciidoctor-pdf`?

> As for using it, no, I was not able to use it before installing ghostscript. I was getting timeout errors when the code ran which is what made me focus more on the install error messages.

I think it's unrelated (or at least I hope it's unrelated) because ghostscript is not used when you convert an AsciiDoc document to PDF.
So if you uninstall ghostscript it should work. Not sure why you were getting timeout errors though...

**Comment by woodbe** [comment]
Ok, I have to admit a lot of ignorance here. I am unable to get it to uninstall using npm (the ghostscript I can do easily, but I'm not really familiar with npm). I am running powershell as admin and get this error when I am trying to uninstall (I also tried with just "asciidoctor-pdf" with the same result).

PS C:\WINDOWS\system32> npm uninstall @asciidoctor/core asciidoctor-pdf
npm WARN saveError ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.

up to date in 0.271s
found 0 vulnerabilities

I will be glad to help, I'm just not sure exactly what I need to do (sorry).

**Comment by woodbe** [comment]
OK, I figured out the uninstall (I was missing the "-g").
[install_logs.zip](https://github.com/Mogztter/asciidoctor-pdf.js/files/4182283/install_logs.zip)

I uninstalled everything, moved the gs folder and re-ran the installation. When I run it after getting the errors during install I get this message

_Unable to generate the PDF - Error: TimeoutError: Navigation timeout of 30000 ms exceeded_

I have attached the logs from the installation attempts during the last week. Let me know if you need something else.

**Comment by Mogztter** [comment]
> OK, I figured out the uninstall (I was missing the "-g").

Indeed, if you've installed `asciidoctor-pdf` globally you need the `-g` option to uninstall it.

> I have attached the logs from the installation attempts during the last week. 

I can't find the error about ghoscript in your logs but I found other errors:

**6 February**

```
711 error code ENOENT
712 error syscall spawn git
713 error path git
714 error errno ENOENT
715 error enoent Error while executing:
715 error enoent undefined ls-remote -h -t git://github.com/mathjax/MathJax-src.git
715 error enoent
715 error enoent
715 error enoent spawn git ENOENT
716 error enoent This is related to npm not being able to find a file.
717 verbose exit [ 1, true ]
```

MathJax is using a git dependency and as a consequence `git` is required. See: https://github.com/Mogztter/asciidoctor-pdf.js/issues/124

I've reported this issue upstream and it should be fixed in the next version of MathJax (so `git` won't be required anymore).

Did you install git?

**8 February**

```
699 error code EEXIST
1700 error path C:\Program Files\nodejs\asciidoctor-pdf
1701 error Refusing to delete C:\Program Files\nodejs\asciidoctor-pdf: is outside C:\Program Files\nodejs\node_modules\asciidoctor-pdf and not a link
1702 error File exists: C:\Program Files\nodejs\asciidoctor-pdf
1703 error Remove the existing file and try again, or run npm
1704 error with --force to overwrite files recklessly.
```

I think you are trying to reinstall `asciidoctor-pdf` but it's already installed.

> Unable to generate the PDF - Error: TimeoutError: Navigation timeout of 30000 ms exceeded

You get this error every time?
Could you try to run with `--verbose` and copy the output? Could you also try to run with `--preview` and then open the developer tools in Chrome to debug it further?

Thanks for all this information, hopefully we will soon find the root cause :wink:

**Comment by woodbe** [comment]
Thanks. I did eventually install git, and I hadn't been sure about the installation, so yes, I definitely tried installing several times (and I wasn't sure how to uninstall, hence the problems.

I just ran the --verbose and got this:

require undefined
backend undefined
doctype undefined
standalone true
section-numbers false
failure-level FATAL
quiet false
verbose true
timings false
trace false
base-dir undefined
destination-dir undefined
verbose-mode 2
attributes
options {"safe":"unsafe","standalone":true,"failure_level":4,"verbose":2,"timings":false,"trace":false,"mkdirs":true,"attributes":[]}
converting file .\cPP-template.adoc
Unable to generate the PDF - Error: TimeoutError: Navigation timeout of 30000 ms exceeded

The preview just gave the timeout error (after launching the Chrome window). It does generate the HTML.
[Templates.zip](https://github.com/Mogztter/asciidoctor-pdf.js/files/4182728/Templates.zip)


On the off chance it could help, I'm attaching the adoc file and he HTML that is being generated. There are some custom admonitions (which is a different question since I don't know how to get those to be properly included here though I can do it in the "normal" asciidoctor).

**Comment by Mogztter** [comment]
Thanks for sharing.
I've noticed that Paged.js is looping:

![loop](https://user-images.githubusercontent.com/333276/74186009-16153180-4c4a-11ea-8a96-66d04b9ac49f.gif)

As you can see, Paged.js is in an infinite loop.
But I was still able to generate a PDF from your file (on Linux): [cPP-template.pdf](https://github.com/Mogztter/asciidoctor-pdf.js/files/4182865/cPP-template.pdf)


Not sure why on your machine Chrome is not able to navigate to the page within 30 seconds. Maybe on Windows Chrome is waiting for the JavaScript to complete but since it never completes... or maybe your machine is performing poorly?
We could increase the timeout (or disable the timeout completely) but I feel like 30 seconds is already a lot.

Would you be able to check on another machine or on Linux?

**Comment by woodbe** [comment]
Yeah, I opened the file and noticed the infinite loop, thought that was odd.

I probably can't try on a Linux box until later this week, but I will see if I can get a Linux VM working (not sure, I'm on a business trip at the moment). The system is otherwise OK, so I'm not sure what is going on (but I figured providing both files would help show what is going on anyway).

**Comment by Mogztter** [comment]
@woodbe I've released a new version with a new version of Paged.js. Could you please give it a try and report back?

**Comment by Mogztter** [comment]
Closing, feel free to open a new issue (ideally with a reproduction case) if you still have problems with the latest release.
