### ISSUE TITLE
Cross references pointing to files that contain tags do not function properly

### ISSUE THREAD

**Issue by Patrick-LuoYu** [Mogztter/asciidoctor-web-pdf#625]
Assume the following files:

|--chapter.adoc
|--chpaters
    |--chpater-1.adoc
    |--chapter-2.adoc
    |--chapter-2
        |--first-steps.adoc

chpater.doc

```asciidoc
= Book Title
:doctype: book

include::chapters/chapter-1.adoc[]

include::chapters/chapter-2.adoc[]
```
chapter-1.adoc

```asciidoc
== Chapter 1

We cover a little bit here.
The rest you can find in <<chapters/chapter-2.adoc#_chapter_2,Chapter 2>>.
```

chapter-2.adoc

```asciidoc
== Chapter 2

Prepare to be educated.
This chapter has it all!

To begin, jump to <<chapters/chapter-2/first-steps.adoc#_first_steps,first steps>>.


// tag::test[]

test

// end::test[]

<<<

include::chapter-2/first-steps.adoc[]
```

first-steps.adoc

```asciidoc
=== First Steps

Let's start small.

include::../chapter-2.adoc[tags=test]
```

If we convert `chapter.adoc` into a PDF file, the cross reference `<<chapters/chapter-2.adoc#_chapter_2,Chapter 2>>` in `chapter-1.adoc` is faulty. However, if we remove the tag statements in `chapter-2.adoc` or remove  `include::../chapter-2.adoc[tags=test]` in `first-steps.adoc`, everything works fine.

Please help resolve the problem. Thanks!

**Comment by Mogztter** [comment]
Since I can reproduce this behavior using `asciidoctor` CLI, I assume that this is not specific to `asciidoctor-web-pdf`` (which relies on `asciidoctor`).

I'm also unsure if this is the intended behavior or not. Please ask your question in the `#users` stream of the community chat at [asciidoctor.zulipchat.com](https://asciidoctor.zulipchat.com/). Thanks!
